# Generated by Django 6.0.5 on 2026-06-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_Price',
            new_name='selling_price',
        ),
    ]
