# Generated by Django 6.0.5 on 2026-06-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_selling_price_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_images',
            new_name='product_image',
        ),
    ]
