# Generated by Django 6.0.5 on 2026-06-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
    ]
