# Generated by Django 6.0.5 on 2026-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodapp',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
